### PR TITLE
TypeScript migration

### LINKED ISSUE #31: Feature: eeg-pipes in React Native
I am utilizing eeg-pipes in conjunction with a React Native Android app. I love eeg-pipes's API, but Babel doesn't run unless I have a debugger window open in the browser:

screenshot_20181024-193416

I presume the transpiler needs a browser window to run? I am quite new to front-end and am more than willing to add this feature myself and do a pull request; I may need a suggestion regarding where to start, however.

### PR DESCRIPTION
**Pull request by alexcastillo**
Includes:

* All files have been migrated to TypeScript
* New build process with TypeScript, Parcel and Rollup
* Outputs ESM, CJS, UMD and Electron bundles (see readme)

Should fix #31 and #23

### CODE REVIEW

**Comment by wtcross** [comment]
@alexcastillo, thank you for putting work into TypeScript support. Do you think we can get this merged in at some point soon? It was approved on Jan 16

**Comment by alexcastillo** [comment]
Sure, I'll make a release later today.

**Comment by andrewjaykeller** [comment]
Great work!!!!

**Comment by wtcross** [comment]
Thanks for this! I'm building a Svelte application using TypeScript and Rollup as the module bundler. It appears that when I import the `@neurosity/pipes` package with `import { bandpassFilter, epoch, fft } from "@neurosity/pipes"` I get the browser distribution, which requires parcel. If I use `import { bandpassFilter, epoch, fft } from "@neurosity/pipes/dist/esm"` it compiles, but I get the following error in the browser due to the `dsp.js` dependency:

```
dsp.js:60 Uncaught TypeError: Cannot read property 'Float64Array' of undefined
    at setupTypedArray (dsp.js:60)
    at dsp.js:77
    at createCommonjsModule (index.mjs:1640)
    at bandpassFilter.js:85
    at main.ts:6
```

This is very likely an issue due to my rollup/typescript configuration, but wanted to check to see if you know what the issue is.

**Comment by alexcastillo** [comment]
Hey Tyler,

I haven’t this issue before, but it does sound like a config issue.

Any luck so far?

Best,
Alex

**Pull request merged**
